packages:
  - "packages/*"
  - "examples/*"
  - "!examples/lynx-community-crossplatform"
  - "!examples/lynx-official-examples"

onlyBuiltDependencies:
  - esbuild
allowBuilds:
  "@biomejs/biome": false
  "@swc/core": true
  core-js: true
  electron: false
  electron-winstaller: false
  esbuild: true
