import { readFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { intlPolyfillPlan, type IntlCapability } from "@lynxship/i18n";
import type { I18nSetupPlan } from "./types.js";
import {
  discoverIntlCapabilities,
  discoverLocales,
  projectRelative,
  readProjectPackage,
  resolveEntryFile,
} from "./discovery.js";

const PERSISTENCE_PACKAGES = ["@lynxship/device-storage"] as const;

const BASE_PACKAGES = ["@lynxship/i18n", "i18next@^26.0.0"] as const;

const CAPABILITY_PREREQUISITES: Readonly<
  Partial<Record<IntlCapability, readonly IntlCapability[]>>
> = {
  PluralRules: ["getCanonicalLocales", "Locale"],
  NumberFormat: ["getCanonicalLocales", "Locale", "PluralRules"],
  DateTimeFormat: ["getCanonicalLocales", "Locale", "NumberFormat"],
  RelativeTimeFormat: ["getCanonicalLocales", "Locale"],
  ListFormat: ["getCanonicalLocales", "Locale"],
  DisplayNames: ["getCanonicalLocales", "Locale"],
  Segmenter: ["getCanonicalLocales", "Locale"],
  DurationFormat: ["getCanonicalLocales", "Locale"],
};

export async function createI18nSetupPlan(options: {
  root: string;
  entry?: string;
  capabilities?: readonly IntlCapability[];
  locales?: readonly string[];
  persistence: boolean;
}): Promise<I18nSetupPlan> {
  const entryFile = await resolveEntryFile(options.root, options.entry);
  const packageJson = await readProjectPackage(options.root);
  const dependencies = {
    ...packageJson.dependencies,
    ...packageJson.devDependencies,
  };
  const capabilities = options.capabilities?.length
    ? [...new Set(options.capabilities)]
    : await discoverIntlCapabilities(options.root);
  const expanded = expandCapabilities(capabilities);
  const packages = [
    ...BASE_PACKAGES.filter(
      (packageName) => !hasDependency(dependencies, packageName),
    ),
    ...(options.persistence &&
    !hasDependency(dependencies, "@lynxship/device-storage")
      ? PERSISTENCE_PACKAGES
      : []),
    ...expanded
      .map((capability) => intlPolyfillPlan(capability).packageName)
      .filter((packageName) => !hasDependency(dependencies, packageName)),
  ];
  const polyfillFile = join(
    options.root,
    "src",
    "lynxship",
    "i18n-polyfills.ts",
  );
  const entrySource = await readFile(entryFile, "utf8");
  const polyfillSource = await readFile(polyfillFile, "utf8").catch(() => "");
  return {
    entryFile: projectRelative(options.root, entryFile),
    polyfillFile: projectRelative(options.root, polyfillFile),
    locales: options.locales?.length
      ? [...options.locales]
      : await discoverLocales(options.root),
    capabilities: expanded,
    packages,
    persistence: options.persistence,
    entryAlreadyPatched: entrySource.includes("./lynxship/i18n-polyfills.js"),
    polyfillAlreadyGenerated: polyfillSource.length > 0,
  };
}

export function renderPolyfillSource(plan: I18nSetupPlan): string {
  const imports = plan.capabilities.flatMap((capability) => {
    const item = intlPolyfillPlan(capability);
    const localeData = item.localeDataEntryPoint
      ? plan.locales.map((locale) =>
          item.localeDataEntryPoint.replace("{locale}", locale),
        )
      : [];
    return [item.setupEntryPoint, ...localeData];
  });
  return [
    "/* Generated by `lynxship i18n setup`. Do not edit by hand. */",
    "/* Imports are intentionally static so native Lynx bundles stay offline and reproducible. */",
    ...[...new Set(imports)].map((entry) => `import ${JSON.stringify(entry)};`),
    "",
  ].join("\n");
}

export function entryImportPath(plan: I18nSetupPlan): string {
  const entryDirectory = dirname(plan.entryFile);
  const polyfillPath = relative(entryDirectory, plan.polyfillFile)
    .replaceAll("\\", "/")
    .replace(/\.tsx?$/, ".js");
  return polyfillPath.startsWith(".") ? polyfillPath : `./${polyfillPath}`;
}

function expandCapabilities(
  capabilities: readonly IntlCapability[],
): IntlCapability[] {
  const expanded = new Set<IntlCapability>();
  const add = (capability: IntlCapability): void => {
    if (expanded.has(capability)) return;
    for (const prerequisite of CAPABILITY_PREREQUISITES[capability] ?? [])
      add(prerequisite);
    expanded.add(capability);
  };
  for (const capability of capabilities) add(capability);
  return [...expanded];
}

function hasDependency(
  dependencies: Readonly<Record<string, string | undefined>>,
  packageName: string,
): boolean {
  const separator = packageName.startsWith("@")
    ? packageName.indexOf("@", 1)
    : packageName.indexOf("@");
  const name = separator > 0 ? packageName.slice(0, separator) : packageName;
  return Object.prototype.hasOwnProperty.call(dependencies, name);
}
