import org.gradle.api.initialization.resolve.RepositoriesMode

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "LynxShipAndroidDemo"
include ":app"
include ":lynxship-sdk-android"
project(":lynxship-sdk-android").projectDir = file("../../../packages/sdk-android")
