import org.gradle.api.initialization.resolve.RepositoriesMode

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "LynxShipAndroidDemo"
include ":app"
include ":lynxship-sdk-android"
project(":lynxship-sdk-android").projectDir = file("../../../packages/sdk-android")
include ":lynxship-device-storage"
project(":lynxship-device-storage").projectDir = file("../../../packages/device-storage/android")
include ":lynxship-permissions"
project(":lynxship-permissions").projectDir = file("../../../packages/permissions/android")
include ":lynxship-media"
project(":lynxship-media").projectDir = file("../../../packages/media/android")
include ":lynxship-notifications"
project(":lynxship-notifications").projectDir = file("../../../packages/notifications/android")
include ":lynxship-navigation"
project(":lynxship-navigation").projectDir = file("../../../packages/navigation/android")
